# Generated by Django 2.1.3 on 2018-11-17 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.CharField(max_length=2048)),
                ('options', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='current_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_state', to='Adventure.State'),
        ),
        migrations.AddField(
            model_name='option',
            name='next_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_state', to='Adventure.State'),
        ),
    ]
