# Generated by Django 2.1.3 on 2018-11-19 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adventure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_state', to='Adventure.State')),
            ],
        ),
    ]
