# Generated by Django 2.1.3 on 2018-11-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adventure', '0002_statemachine'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='state_name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
